"""Compatibility facade for reverse-prompt services."""
from __future__ import annotations

from ..config import settings  # noqa: F401 - retained for legacy monkeypatches
from ..schemas import ReverseBatchCreate, ReverseIn, ReverseOperationCreate  # noqa: F401
from . import credits, gateway, usage  # noqa: F401
from . import reverse_batches as _reverse_batches_module  # noqa: E402
from . import reverse_lifecycle as _reverse_lifecycle_module  # noqa: E402
from . import reverse_operation_records as _reverse_operation_records_module  # noqa: E402
from . import reverse_quotes as _reverse_quotes_module  # noqa: E402
from . import reverse_revisions as _reverse_revisions_module  # noqa: E402
from . import reverse_runner as _reverse_runner_module  # noqa: E402
from .compat_facade import (  # noqa: E402
    install_assignment_forwarding as _install_assignment_forwarding,
)
from .content_safety import assert_text_allowed  # noqa: F401
from .model_gateway_config import runtime_config_for_model  # noqa: F401
from .reverse_batches import (  # noqa: F401, E402
    _assert_quote_replay_binding,
    _batch_item_rows,
    _batch_operation_client_request_id,
    _derived_batch_status,
    batch_operation_bodies,
    batch_request_fingerprint,
    batch_request_snapshot,
    create_batch,
    create_quoted_batch,
    find_idempotent_batch,
    find_quoted_idempotent_batch,
    get_owned_batch,
    list_owned_batches,
    request_batch_cancel,
    serialize_batch,
    sync_batch_for_operation,
    sync_batch_state,
)
from .reverse_lifecycle import (  # noqa: F401, E402
    _expire_cover_confirmation,
    _refund_locked,
    confirm_cover,
    enqueue_operation,
    fail_operation,
    fail_queued_submission,
    request_cancel,
    transition_legacy_to_confirmation,
)
from .reverse_operation_records import (  # noqa: F401, E402
    _assert_operation_quote_replay,
    _attach_operation_project_inputs,
    _create_operation_record,
    _create_quoted_operation,
    _get_owned,
    _operation_context,
    _operation_snapshots,
    create_legacy_operation,
    create_operation,
    create_quoted_operation,
    find_idempotent_operation,
    find_quoted_idempotent_operation,
    get_owned_operation,
    list_owned_operations,
    serialize_operation,
)
from .reverse_quotes import (  # noqa: F401
    _ASSET_FIELDS,
    _FOCUS_INSTRUCTIONS,
    _REFERENCE_ROLE_INSTRUCTIONS,
    _SECRET_KEY_PARTS,
    _SNAPSHOT_FIELDS,
    BIZ_TYPE,
    CONFIRMATION_TTL,
    IMAGE_EVIDENCE_TARGETS,
    OPERATION_STATUSES,
    REPUBLISH_AFTER,
    TERMINAL_STATUSES,
    ReverseOperationConflict,
    ReverseOperationInvalid,
    ReverseOperationNotFound,
    _assert_snapshot_has_no_secrets,
    _assert_supported_vision_runtime,
    _aware,
    _body_dict,
    _clean_asset,
    _log_operation_event,
    _model_snapshot,
    _normalized_provider_credit,
    _primary_asset_url,
    _provider_cost_call_detail,
    _provider_cost_policy_for_model,
    _provider_cost_policy_from_pricing,
    _reverse_audio_surcharge_for_model,
    _reverse_cost_for_model,
    _source_ranges_payload,
    _source_type_for_request,
    _template_snapshot,
    assert_supported_vision_runtime,
    model_snapshot,
    prepare_reverse_quote,
    quote_request_fingerprint,
    request_fingerprint,
    reverse_pricing_snapshot,
    reverse_request_snapshot,
    reverse_template_snapshot,
    sanitize_workspace_snapshot,
    utcnow,
)
from .reverse_revisions import (  # noqa: F401, E402
    _TIMED_SHOT_REFERENCE_SPECS,
    _finite_float,
    _invalidate_timeline_compilation,
    _latest_timeline_revision,
    _rebind_shot_timed_evidence,
    _reference_id,
    _revision_shots,
    _shot_by_id,
    _timed_evidence_sources,
    _timed_row_overlaps_shot,
    apply_result_revision,
    attach_shot_reanalysis_context,
    build_retry_operation_body,
    create_result_revision,
    edit_shot_timeline,
    get_feedback,
    list_result_revisions,
    prepare_shot_generation,
    retry_operation,
    revision_shots,
    shot_reanalysis_body,
    upsert_feedback,
)
from .reverse_runner import (  # noqa: F401, E402
    _OCR_CLAIM_QUOTE_PAIRS,
    _apply_image_ocr_gate_to_text,
    _audio_analysis_for_request,
    _claim_operation,
    _fail_stale_running,
    _fallback_reference_fingerprints,
    _finalize_evidence_bound_video_result,
    _finish_success,
    _gateway_accepts,
    _has_timestamped_audio_evidence,
    _history_title,
    _merge_completed_shot_reanalysis,
    _merge_video_analysis_result,
    _pause_for_cover,
    _record_gateway_failure,
    _remember_history,
    _replace_ocr_claim,
    _set_phase,
    _tidy_gated_text_field,
    reap_operations,
    run_operation,
    validate_reverse_result,
)

_install_assignment_forwarding(
    __name__,
    (
        _reverse_batches_module,
        _reverse_lifecycle_module,
        _reverse_operation_records_module,
        _reverse_quotes_module,
        _reverse_revisions_module,
        _reverse_runner_module,
    ),
)
