import { buildStudioDerivedViewState } from "./viewModel";
import { generationRequiresPendingUpload } from "./generationUploadPolicy";

function buildSubmitBarProps(foundation, model, task, generation, view) {
  const missingVideoFirstFrame = Boolean(
    model.videoRequiresFirstFrame && foundation.selected?.type !== "image",
  );
  const missingRequiredSource = Boolean(
    (foundation.isEditMode && !foundation.productAsset) || missingVideoFirstFrame,
  );
  const uploadBlocked = generationRequiresPendingUpload({
    uploading: foundation.uploading,
    uploadingRole: foundation.uploadingRole,
    selected: foundation.selected,
  });
  const missingRequiredSourceLabel = missingVideoFirstFrame
    ? "请先上传视频首帧"
    : foundation.portraitGenerationMode
      ? "请先上传人物"
      : foundation.productGenerationMode
        ? "请先上传产品"
        : "请先上传图片";
  const handleModelSwitchRequired = () => {
    if (!model.modelSwitchMessage) return;
    foundation.setMsg(model.modelSwitchMessage);
    foundation.notify.error(model.modelSwitchMessage, {
      title: `请切换${foundation.category === "video" ? "视频" : "图片"}模型`,
      duration: 6000,
    });
  };

  return {
    category: foundation.category,
    videoFinalCost: view.videoFinalCost,
    estCost: view.estCost,
    imageCount: view.imageCount,
    videoDuration: view.videoDuration,
    vResolution: foundation.vResolution,
    submit: generation.submit,
    missingRequiredSource,
    missingRequiredSourceLabel,
    videoRequiresFirstFrame: model.videoRequiresFirstFrame,
    modelSwitchRequired: model.modelSwitchRequired,
    modelSwitchMessage: model.modelSwitchMessage,
    onModelSwitchRequired: handleModelSwitchRequired,
    structuredDirty: foundation.structuredDirty,
    submitting: generation.submitting,
    parsing: foundation.parsing,
    uploadBlocked,
    reversing: foundation.reversing,
    productProfiling: foundation.productProfiling,
    task: task.task,
    currentModelEnabled: view.currentModelEnabled,
    running: view.running,
    submitLabel: view.submitLabel,
  };
}

function buildCreationController(domains, view, submitBarProps) {
  const { foundation, model, prompt, task, reverse, reference, generation } = domains;
  return {
    mode: {
      cfg: foundation.cfg,
      creationMode: foundation.creationMode,
      modelEnabled: model.modelEnabled,
      switchCreationMode: prompt.switchCreationMode,
      currentModelEnabled: view.currentModelEnabled,
      category: foundation.category,
      isEditMode: foundation.isEditMode,
      isImageEditMode: foundation.isImageEditMode,
      subjectMode: foundation.subjectMode,
      portraitGenerationMode: foundation.portraitGenerationMode,
      productGenerationMode: foundation.productGenerationMode,
      changeEditSubjectMode: prompt.changeEditSubjectMode,
      imageEditProductMode: foundation.imageEditProductMode,
    },
    prompt: {
      prompt: foundation.prompt,
      promptPlaceholder: view.promptPlaceholder,
      editReadySteps: view.editReadySteps,
      editStyleKeys: view.editStyleKeys,
      updatePromptFromUser: prompt.updatePromptFromUser,
      setPromptDirty: foundation.setPromptDirty,
      optimizeDirectPrompt: prompt.optimize,
      promptReadyForOptimization: prompt.ready,
      selectedPromptModelConfigId: model.selectedPromptModelConfigId,
      optimizingPrompt: prompt.optimizing,
      promptOptimizationProposal: prompt.proposal,
      promptOptimizationSetting: prompt.setting,
      selectedPromptModel: model.selectedPromptModel,
      changePromptOptimizationSetting: prompt.changeSetting,
      acceptPromptOptimization: prompt.accept,
      rejectPromptOptimization: prompt.reject,
      promptOptimizationUndoAvailable: prompt.undoAvailable,
      undoAcceptedPromptOptimization: prompt.undoAccepted,
      promptModelOptions: model.promptModelOptions,
      changeModelSelection: prompt.changeModelSelection,
      negative: foundation.negative,
      showNegative: foundation.showNegative,
      setShowNegative: foundation.setShowNegative,
      setNegative: foundation.setNegative,
      setNegativeTouched: foundation.setNegativeTouched,
      structured: foundation.structured,
      recompose: reference.recompose,
      undoStructuredChanges: reference.undoStructuredChanges,
      structuredDirty: foundation.structuredDirty,
      promptDirty: foundation.promptDirty,
      structuredSource: foundation.structuredSource,
      promptSourceSignature: foundation.promptSourceSignature,
      lastReversePromptRef: reverse.lastReversePromptRef,
      promptSaveTitle: foundation.promptSaveTitle,
      promptSaveCategory: foundation.promptSaveCategory,
      promptSaveFavorite: foundation.promptSaveFavorite,
      setPromptSaveTitle: foundation.setPromptSaveTitle,
      setPromptSaveCategory: foundation.setPromptSaveCategory,
      setPromptSaveFavorite: foundation.setPromptSaveFavorite,
      saveReversePromptToLibrary: reverse.saveReversePromptToLibrary,
    },
    workspace: {
      clearCurrentWorkspace: reference.clearCurrentWorkspace,
      clearAllWorkspaces: reference.clearAllWorkspaces,
      selected: foundation.selected,
      assets: foundation.assets,
      variationSource: foundation.variationSource,
      setWorkspacePatch: foundation.setWorkspacePatch,
      saveCreationRecipe: reverse.saveCreationRecipe,
      recipesEnabled: foundation.recipesEnabled,
    },
    generation: {
      selectedGenerationModelConfigId: model.selectedGenerationModelConfigId,
      generationModelOptions: model.generationModelOptions,
      changeGenerationModelSelection: prompt.changeGenerationModelSelection,
      productVideoStrategySelection: model.productVideoStrategySelection,
      effectiveProductVideoTemplate: model.effectiveProductVideoTemplate,
      changeProductVideoTemplate: prompt.changeProductVideoTemplate,
      submit: generation.submit,
      ratioOptions: view.ratioOptions,
      ratio: foundation.ratio,
      setRatio: foundation.setRatio,
      imageQuality: foundation.imageQuality,
      setImageQuality: foundation.setImageQuality,
      currentImageSize: view.currentImageSize,
      maxImageN: view.maxImageN,
      imageCount: view.imageCount,
      n: foundation.n,
      setN: foundation.setN,
      minVideoDuration: view.minVideoDuration,
      maxVideoDuration: view.maxVideoDuration,
      videoDuration: view.videoDuration,
      videoQualityOptions: view.videoQualityOptions,
      vDuration: foundation.vDuration,
      setVDuration: foundation.setVDuration,
      vResolution: foundation.vResolution,
      setVResolution: foundation.setVResolution,
      seed: foundation.seed,
      setSeed: foundation.setSeed,
      editMaskMode: foundation.editMaskMode,
      setEditMaskMode: foundation.setEditMaskMode,
      maskEditSupported: model.maskEditSupported,
      productPixelLockMode: foundation.productPixelLockMode,
      setProductPixelLockMode: foundation.setProductPixelLockMode,
      submitting: generation.submitting,
      selectedGenerationModel: model.selectedGenerationModel,
      targetModelId: model.targetModelId,
      compileStoryboardShot: reverse.compileStoryboardShot,
      applyStoryboardShot: reverse.applyStoryboardShot,
      handleGenerationSubmitted: task.handleGenerationSubmitted,
      requestQuoteConfirmation: model.requestQuoteConfirmation,
      videoCompositionEnabled: foundation.videoCompositionEnabled,
    },
    reference: buildReferenceController(domains),
    reverse: buildReverseController(domains, view),
    ui: {
      submitBarProps,
      refOpen: foundation.refOpen,
      setRefOpen: foundation.setRefOpen,
      structOpen: foundation.structOpen,
      setStructOpen: foundation.setStructOpen,
      notify: foundation.notify,
      msg: foundation.msg,
      setMsg: foundation.setMsg,
    },
  };
}

function buildReferenceController({ foundation, model, reverse, reference }) {
  return {
    url: foundation.url,
    updateReferenceUrl: reference.updateReferenceUrl,
    lastFrameAsset: foundation.lastFrameAsset,
    productAsset: foundation.productAsset,
    productProfile: foundation.productProfile,
    portraitProfile: foundation.portraitProfile,
    parsing: foundation.parsing,
    uploading: foundation.uploading,
    productProfiling: foundation.productProfiling,
    subjectProtection: foundation.subjectProtection,
    subjectProtectionLoading: foundation.subjectProtectionLoading,
    effectiveLastFrameAsset: model.effectiveLastFrameAsset,
    firstLastFrameEnabled: model.firstLastFrameEnabled,
    videoRequiresFirstFrame: model.videoRequiresFirstFrame,
    productDetailAssets: foundation.productDetailAssets,
    productDetailValidation: model.productDetailValidation,
    productDetailLimit: model.productDetailLimit,
    appliedUrl: foundation.appliedUrl,
    profileOperation: foundation.profileOperation,
    reverseSources: foundation.reverseSources,
    imageUploadInputRef: reference.imageUploadInputRef,
    productUploadInputRef: reference.productUploadInputRef,
    productDetailUploadInputRef: reference.productDetailUploadInputRef,
    lastFrameUploadInputRef: reference.lastFrameUploadInputRef,
    videoUploadInputRef: reference.videoUploadInputRef,
    clearRef: reference.clearRef,
    clearProductAsset: reference.clearProductAsset,
    doParse: reverse.doParse,
    doUploadImage: reference.doUploadImage,
    doUploadProductImage: reference.doUploadProductImage,
    doUploadProductDetailImages: reference.doUploadProductDetailImages,
    doUploadLastFrameImage: reference.doUploadLastFrameImage,
    setAssetPicker: foundation.setAssetPicker,
    doUploadVideo: reference.doUploadVideo,
    pickAsset: reverse.pickAsset,
  };
}

function buildReverseController({ foundation, model, reverse }, view) {
  const resolvedReverseOperation = reverse.reverseOperationForPendingResult();
  const resolvedReversing = resolvedReverseOperation
    ? ["queued", "running"].includes(resolvedReverseOperation.status)
    : foundation.reversing;
  return {
    reversing: resolvedReversing,
    batchReverseAssets: foundation.batchReverseAssets,
    pendingReverseResult: foundation.pendingReverseResult,
    reverseEnabled: view.reverseEnabled,
    reverseImageCost: view.reverseImageCost,
    selectedReverseCost: view.selectedReverseCost,
    selectedReverseCostLabel: view.selectedReverseCostLabel,
    reverseConfig: foundation.reverseConfig,
    setReverseConfig: foundation.setReverseConfig,
    videoAnalysisPreset: foundation.videoAnalysisPreset,
    reverseVideoPresets: view.reverseVideoPresets,
    reverseVideoAnalysis: foundation.reverseVideoAnalysis,
    reverseOperation: resolvedReverseOperation || reverse.reverseOperation,
    workspaceReverseOperation: foundation.workspaceReverseOperation,
    reverseBatch: reverse.reverseBatch,
    recentReverseBatches: reverse.recentReverseBatches,
    reverseBatchBusyAction: reverse.reverseBatchBusyAction,
    reverseActionBusy: foundation.reverseActionBusy,
    reverseBatchEnabled: foundation.reverseBatchEnabled,
    visionModelOptions: model.visionModelOptions,
    selectedVisionModelConfigId: model.selectedVisionModelConfigId,
    setVideoAnalysisPreset: foundation.setVideoAnalysisPreset,
    doReverse: reverse.doReverse,
    confirmReverseCover: reverse.confirmReverseCover,
    cancelReverseOperationForMode: reverse.cancelReverseOperationForMode,
    toggleBatchReverseAsset: reverse.toggleBatchReverseAsset,
    removeBatchReverseAsset: reverse.removeBatchReverseAsset,
    startReverseBatch: reverse.startReverseBatch,
    cancelReverseBatch: reverse.cancelReverseBatch,
    openReverseBatch: reverse.openReverseBatch,
    openRecentReverseOperation: reverse.openRecentReverseOperation,
    retryReverse: reverse.retryReverse,
    saveReverseBatchRecipes: reverse.saveReverseBatchRecipes,
    reverseOperationForPendingResult: reverse.reverseOperationForPendingResult,
    reverseResultTab: foundation.reverseResultTab,
    reverseResultRevisions: foundation.reverseResultRevisions,
    reverseAppliedVersion: foundation.reverseAppliedVersion,
    reverseAppliedRevisionId: foundation.reverseAppliedRevisionId,
    reverseFeedback: foundation.reverseFeedback,
    reverseUndoSnapshot: foundation.reverseUndoSnapshot,
    applyPendingReverseResult: reverse.applyPendingReverseResult,
    undoAppliedReverseResult: reverse.undoAppliedReverseResult,
    savePendingReverseVersion: reverse.savePendingReverseVersion,
    submitReverseFeedback: reverse.submitReverseFeedback,
    restoreReverseRevision: reverse.restoreReverseRevision,
    reverseApplyConflict: foundation.reverseApplyConflict,
    recentReverseOperations: reverse.recentReverseOperations,
    recentReverseLoading: reverse.recentReverseLoading,
    recentReverseError: reverse.recentReverseError,
    recentReverseBusyId: foundation.recentReverseBusyId,
    refreshRecentReverseOperations: reverse.refreshRecentReverseOperations,
  };
}

function buildResultsController({ foundation, model, task, reverse, reference, generation }) {
  return {
    resultsRef: task.resultsRef,
    task: task.task,
    runningSnapshot: task.runningSnapshot,
    showRunningProgress: task.showRunningProgress,
    trackingLost: task.trackingLost,
    backgroundTasks: task.backgroundTasks,
    submitting: generation.submitting,
    works: task.visibleWorks,
    lightbox: task.lightbox,
    setLightbox: task.setLightbox,
    busyAssetIds: task.busyAssetIds,
    refreshActiveTask: task.refreshActiveTask,
    cancelActiveTask: task.cancelActiveTask,
    taskEtaText: task.taskEtaText,
    worksError: task.worksError,
    loadWorks: task.loadWorks,
    dismissBackgroundTask: task.dismissBackgroundTask,
    cancelBackgroundTask: task.cancelBackgroundTask,
    unlock: task.unlock,
    download: task.download,
    createImageVariation: reference.createImageVariation,
    selected: foundation.selected,
    generationReverseOperationId: reverse.generationReverseOperationId,
    generationReverseRevisionId: reverse.generationReverseRevisionId,
    selectedGenerationModelConfigId: model.selectedGenerationModelConfigId,
    reproductionVideoComposition: reverse.reproductionVideoComposition,
    requestQuoteConfirmation: model.requestQuoteConfirmation,
    handleReproductionCorrectionCreated: task.handleReproductionCorrectionCreated,
    handleReproductionRemediationCreated: task.handleReproductionRemediationCreated,
    handleReproductionRemediationExecutionSubmitted:
      task.handleReproductionRemediationExecutionSubmitted,
    reproductionAssessmentEnabled: foundation.reproductionAssessmentEnabled,
    worksWindow: task.worksWindow,
  };
}

function buildAssetPickerController({ foundation, model, reverse, reference }) {
  return {
    request: foundation.assetPicker,
    reverseBatchEnabled: foundation.reverseBatchEnabled,
    category: foundation.category,
    productDetailLimit: model.productDetailLimit,
    productDetailAssets: foundation.productDetailAssets,
    productAsset: foundation.productAsset,
    effectiveLastFrameAsset: model.effectiveLastFrameAsset,
    selected: foundation.selected,
    batchReverseAssets: foundation.batchReverseAssets,
    uploadInputRefs: {
      image: reference.imageUploadInputRef,
      video: reference.videoUploadInputRef,
      productDetail: reference.productDetailUploadInputRef,
      lastFrame: reference.lastFrameUploadInputRef,
      product: reference.productUploadInputRef,
    },
    setRequest: foundation.setAssetPicker,
    setWorkspacePatch: foundation.setWorkspacePatch,
    selectProductAsset: reference.selectProductAsset,
    selectLastFrameAsset: reference.selectLastFrameAsset,
    selectReferenceAsset: reverse.pickAsset,
    setMsg: foundation.setMsg,
  };
}

export function buildStudioPresentation(domains) {
  const { foundation, model, task, generation } = domains;
  const view = buildStudioDerivedViewState({
    cfg: model.studioCfg,
    creationMode: foundation.creationMode,
    category: foundation.category,
    isEditMode: foundation.isEditMode,
    isImageEditMode: foundation.isImageEditMode,
    subjectMode: foundation.subjectMode,
    productGenerationMode: foundation.productGenerationMode,
    portraitGenerationMode: foundation.portraitGenerationMode,
    task: task.task,
    submitting: generation.submitting,
    selected: foundation.selected,
    productAsset: foundation.productAsset,
    structured: foundation.structured,
    prompt: foundation.prompt,
    ratio: foundation.ratio,
    imageQuality: foundation.imageQuality,
    n: foundation.n,
    vDuration: foundation.vDuration,
    vResolution: foundation.vResolution,
    videoAnalysisPreset: foundation.videoAnalysisPreset,
    reverseConfig: foundation.reverseConfig,
  });
  const submitBarProps = buildSubmitBarProps(foundation, model, task, generation, view);
  return {
    gatewayStatus: view.gatewayStatus,
    submitBarProps,
    creationController: buildCreationController(domains, view, submitBarProps),
    resultsController: buildResultsController(domains),
    assetPickerController: buildAssetPickerController(domains),
  };
}
