"use client";

import useGenerationSubmit from "../useGenerationSubmit";

export default function useStudioGenerationDomain(foundation, model, prompt, task, reverse) {
  const {
    cfg,
    category,
    creationMode,
    isEditMode,
    isImageEditMode,
    subjectMode,
    parsing,
    uploading,
    uploadingRole,
    reversing,
    productProfiling,
    negative,
    promptDirty,
    promptSourceSignature,
    selected,
    productAsset,
    productDetailAssets,
    productProfile,
    productProfileSource,
    portraitProfile,
    portraitProfileSource,
    variationSource,
    structured,
    structuredDirty,
    structuredSource,
    reverseVideoAnalysis,
    reverseConfig,
    ratio,
    imageQuality,
    n,
    seed,
    editMaskMode,
    productPixelLockMode,
    vDuration,
    vResolution,
    productVideoTemplate,
    setMsg,
    setWorkspacePatch,
    refreshMe,
    getOwnerSession,
    refs,
  } = foundation;

  return useGenerationSubmit({
    cfg,
    task: task.task,
    category,
    creationMode,
    isEditMode,
    isImageEditMode,
    subjectMode,
    parsing,
    uploading,
    uploadingRole,
    reversing,
    productProfiling,
    prompt: prompt.promptForGeneration,
    negative,
    promptDirty,
    promptSourceSignature,
    selected,
    lastFrameAsset: model.effectiveLastFrameAsset,
    firstLastFrameEnabled: model.firstLastFrameEnabled,
    productAsset,
    productDetailAssets,
    productProfile,
    productProfileSource,
    portraitProfile,
    portraitProfileSource,
    variationSource,
    structured,
    structuredDirty,
    structuredSource,
    reverseVideoAnalysis,
    analysisFocus: reverseConfig?.analysis_focus || "",
    ratio,
    imageQuality,
    n,
    seed,
    editMaskMode,
    productPixelLockMode,
    vDuration,
    vResolution,
    productVideoTemplate: model.effectiveProductVideoTemplate || productVideoTemplate,
    modelConfigId: model.selectedGenerationModelConfigId,
    reverseOperationId: reverse.generationReverseOperationId,
    reverseRevisionId: reverse.generationReverseRevisionId,
    reviewedImageEvidence: reverse.generationSourceRevision?.payload?.image_evidence || null,
    reverseEvidenceOperation: reverse.reverseOperationForPendingResult(),
    modelOption: model.selectedGenerationModel,
    visionModelConfigId: model.selectedVisionModelConfigId,
    resultsRef: task.resultsRef,
    modelEnabled: model.modelEnabled,
    setMsg,
    setTask: task.setTask,
    setRunningSnapshot: task.setRunningSnapshot,
    setTrackingLost: task.setTrackingLost,
    setWorkspacePatch,
    trackBackgroundTask: task.trackBackgroundTask,
    refreshMe,
    startTracking: task.startTracking,
    onGenerationSubmitted: task.handleGenerationSubmitted,
    subjectProfilePendingRequestRef: refs.subjectProfilePendingRequestRef,
    subjectProfileResultCacheRef: refs.subjectProfileResultCacheRef,
    subjectProfileOperationsRef: refs.subjectProfileOperationsRef,
    trackProfileReverseOperation: reverse.trackProfileReverseOperation,
    getOwnerSession,
    requestQuoteConfirmation: model.requestQuoteConfirmation,
  });
}
